/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./client/index.html",
    "./client/src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Surface colors
        'surface': '#0f131c',
        'surface-dim': '#0f131c',
        'surface-bright': '#353943',
        'surface-container-lowest': '#0a0e17',
        'surface-container-low': '#181b25',
        'surface-container': '#1c1f29',
        'surface-container-high': '#262a34',
        'surface-container-highest': '#31353f',
        'on-surface': '#dfe2ef',
        'on-surface-variant': '#ccc3d8',
        'inverse-surface': '#dfe2ef',
        'inverse-on-surface': '#2c303a',
        
        // Primary colors
        'primary': '#d2bbff',
        'on-primary': '#3f008e',
        'primary-container': '#7c3aed',
        'on-primary-container': '#ede0ff',
        'inverse-primary': '#732ee4',
        'primary-fixed': '#eaddff',
        'primary-fixed-dim': '#d2bbff',
        'on-primary-fixed': '#25005a',
        'on-primary-fixed-variant': '#5a00c6',
        
        // Secondary colors
        'secondary': '#cebdff',
        'on-secondary': '#381385',
        'secondary-container': '#4f319c',
        'on-secondary-container': '#bea8ff',
        'secondary-fixed': '#e8ddff',
        'secondary-fixed-dim': '#cebdff',
        'on-secondary-fixed': '#21005e',
        'on-secondary-fixed-variant': '#4f319c',
        
        // Tertiary colors
        'tertiary': '#7bd0ff',
        'on-tertiary': '#00354a',
        'tertiary-container': '#006e95',
        'on-tertiary-container': '#caeaff',
        'tertiary-fixed': '#c4e7ff',
        'tertiary-fixed-dim': '#7bd0ff',
        'on-tertiary-fixed': '#001e2c',
        'on-tertiary-fixed-variant': '#004c69',
        
        // Other colors
        'outline': '#958da1',
        'outline-variant': '#4a4455',
        'surface-tint': '#d2bbff',
        'background': '#0f131c',
        'on-background': '#dfe2ef',
        'surface-variant': '#31353f',
        
        // Error colors
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        'display-lg': ['Outfit', 'sans-serif'],
        'display-lg-mobile': ['Outfit', 'sans-serif'],
        'headline-xl': ['Outfit', 'sans-serif'],
        'headline-xl-mobile': ['Outfit', 'sans-serif'],
        'headline-lg': ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
        'headline-sm': ['Outfit', 'sans-serif'],
        'body-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '500' }],
        'body-xl': ['18px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
      spacing: {
        'gutter': '1.5rem',
        'gutter-mobile': '1rem',
        'margin': '3rem',
        'margin-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      borderRadius: {
        DEFAULT: '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      boxShadow: {
        'elevation-1': '0 8px 32px -4px rgba(0, 0, 0, 0.45)',
        'elevation-2': '0 12px 40px -6px rgba(0, 0, 0, 0.60), 0 0 20px 2px rgba(124, 58, 237, 0.15)',
        'elevation-3': '0 24px 64px -12px rgba(0, 0, 0, 0.80), 0 0 40px -8px rgba(124, 58, 237, 0.25)',
        'glow-primary': '0 0 24px rgba(124, 58, 237, 0.40)',
        'glow-primary-strong': '0 0 40px rgba(124, 58, 237, 0.60)',
      },
      backdropBlur: {
        'glass-1': '16px',
        'glass-2': '24px',
        'glass-3': '32px',
      },
    },
  },
  plugins: [],
};
